name: chefmind_ai
description: AI-powered cooking assistant app
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  dio: ^5.4.0
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Storage & Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Network & API
  http: ^1.1.2
  
  # Firebase (Compatible versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0
  
  # Image & Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Connectivity
  connectivity_plus: ^6.0.5
  
  # File system
  path_provider: ^2.1.4
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Integration testing
  integration_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Icon generation
  flutter_launcher_icons: ^0.13.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/icons/
    - .env
