// Mocks generated by Mockito 5.4.6 from annotations
// in chefmind_ai/test/infrastructure/repositories/firebase_recipe_rating_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:chefmind_ai/domain/exceptions/app_exceptions.dart' as _i7;
import 'package:chefmind_ai/infrastructure/services/firebase_service.dart'
    as _i9;
import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:cloud_functions/cloud_functions.dart' as _i6;
import 'package:firebase_analytics/firebase_analytics.dart' as _i5;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_storage/firebase_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseStorage_2 extends _i1.SmartFake
    implements _i4.FirebaseStorage {
  _FakeFirebaseStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalytics_3 extends _i1.SmartFake
    implements _i5.FirebaseAnalytics {
  _FakeFirebaseAnalytics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFunctions_4 extends _i1.SmartFake
    implements _i6.FirebaseFunctions {
  _FakeFirebaseFunctions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_5<T extends Object?> extends _i1.SmartFake
    implements _i3.CollectionReference<T> {
  _FakeCollectionReference_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_6<T extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T> {
  _FakeDocumentReference_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReference_7 extends _i1.SmartFake implements _i4.Reference {
  _FakeReference_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_8 extends _i1.SmartFake implements _i3.WriteBatch {
  _FakeWriteBatch_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_9 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppException_10 extends _i1.SmartFake implements _i7.AppException {
  _FakeAppException_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpsCallable_11 extends _i1.SmartFake implements _i6.HttpsCallable {
  _FakeHttpsCallable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_12<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i9.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);

  @override
  _i3.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_1(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i3.FirebaseFirestore);

  @override
  _i4.FirebaseStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i4.FirebaseStorage);

  @override
  _i5.FirebaseAnalytics get analytics => (super.noSuchMethod(
        Invocation.getter(#analytics),
        returnValue: _FakeFirebaseAnalytics_3(
          this,
          Invocation.getter(#analytics),
        ),
      ) as _i5.FirebaseAnalytics);

  @override
  _i6.FirebaseFunctions get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFirebaseFunctions_4(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i6.FirebaseFunctions);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i2.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i8.Stream<_i2.User?>.empty(),
      ) as _i8.Stream<_i2.User?>);

  @override
  _i3.CollectionReference<Map<String, dynamic>> get communityRecipes =>
      (super.noSuchMethod(
        Invocation.getter(#communityRecipes),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
          this,
          Invocation.getter(#communityRecipes),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);

  @override
  _i3.CollectionReference<Map<String, dynamic>> get cookingGroups =>
      (super.noSuchMethod(
        Invocation.getter(#cookingGroups),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
          this,
          Invocation.getter(#cookingGroups),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);

  @override
  _i3.CollectionReference<Map<String, dynamic>> get challenges =>
      (super.noSuchMethod(
        Invocation.getter(#challenges),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
          this,
          Invocation.getter(#challenges),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i3.CollectionReference<Map<String, dynamic>> collection(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #collection,
          [path],
        ),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #collection,
            [path],
          ),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);

  @override
  _i3.DocumentReference<Map<String, dynamic>> doc(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #doc,
          [path],
        ),
        returnValue: _FakeDocumentReference_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #doc,
            [path],
          ),
        ),
      ) as _i3.DocumentReference<Map<String, dynamic>>);

  @override
  _i3.CollectionReference<Map<String, dynamic>> userCollection(
    String? userId,
    String? subcollection,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userCollection,
          [
            userId,
            subcollection,
          ],
        ),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #userCollection,
            [
              userId,
              subcollection,
            ],
          ),
        ),
      ) as _i3.CollectionReference<Map<String, dynamic>>);

  @override
  _i3.DocumentReference<Map<String, dynamic>> userDoc(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #userDoc,
          [userId],
        ),
        returnValue: _FakeDocumentReference_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #userDoc,
            [userId],
          ),
        ),
      ) as _i3.DocumentReference<Map<String, dynamic>>);

  @override
  _i4.Reference storageRef(String? path) => (super.noSuchMethod(
        Invocation.method(
          #storageRef,
          [path],
        ),
        returnValue: _FakeReference_7(
          this,
          Invocation.method(
            #storageRef,
            [path],
          ),
        ),
      ) as _i4.Reference);

  @override
  _i4.Reference userStorageRef(
    String? userId,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userStorageRef,
          [
            userId,
            path,
          ],
        ),
        returnValue: _FakeReference_7(
          this,
          Invocation.method(
            #userStorageRef,
            [
              userId,
              path,
            ],
          ),
        ),
      ) as _i4.Reference);

  @override
  _i3.WriteBatch batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeWriteBatch_8(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i3.WriteBatch);

  @override
  _i3.Transaction runTransaction<T>(
    _i3.TransactionHandler<T>? updateFunction, {
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTransaction,
          [updateFunction],
          {#timeout: timeout},
        ),
        returnValue: _FakeTransaction_9(
          this,
          Invocation.method(
            #runTransaction,
            [updateFunction],
            {#timeout: timeout},
          ),
        ),
      ) as _i3.Transaction);

  @override
  _i7.AppException handleFirebaseException(dynamic error) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleFirebaseException,
          [error],
        ),
        returnValue: _FakeAppException_10(
          this,
          Invocation.method(
            #handleFirebaseException,
            [error],
          ),
        ),
      ) as _i7.AppException);

  @override
  _i8.Future<void> logEvent(
    String? name, [
    Map<String, Object?>? parameters,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [
            name,
            parameters,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setUserProperty(
    String? name,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [
            name,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i6.HttpsCallable httpsCallable(String? name) => (super.noSuchMethod(
        Invocation.method(
          #httpsCallable,
          [name],
        ),
        returnValue: _FakeHttpsCallable_11(
          this,
          Invocation.method(
            #httpsCallable,
            [name],
          ),
        ),
      ) as _i6.HttpsCallable);

  @override
  _i8.Future<T> callFunction<T>(
    String? name, [
    dynamic parameters,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #callFunction,
          [
            name,
            parameters,
          ],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #callFunction,
                  [
                    name,
                    parameters,
                  ],
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_12<T>(
              this,
              Invocation.method(
                #callFunction,
                [
                  name,
                  parameters,
                ],
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
